version: '3.5'
services:
  image-upload-nginx:
    container_name: image-upload-nginx
    image: nginx
    volumes:
      - ./:/var/www:cached
      - ./.devops/local/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=image.upload.test

  image-upload-php:
    container_name: image-upload-php
    image: cyberduck/php-fpm-laravel:7.4
    volumes:
      - ./:/var/www:cached

networks:
  default:
    external:
      name: docker_development